//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUIClient.CriminalServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebUIClient.CriminalServiceReference.ValidationDetail[] DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebUIClient.CriminalServiceReference.ValidationDetail[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationDetail", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Val" +
        "idation.Integration.WCF")]
    [System.SerializableAttribute()]
    public partial class ValidationDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CriminalServiceReference.ICriminalService")]
    public interface ICriminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/Create", ReplyAction="http://tempuri.org/ICriminalService/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebUIClient.CriminalServiceReference.ValidationFault), Action="http://tempuri.org/ICriminalService/CreateValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        void Create(WebClientContracts.CriminalDTO criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/Create", ReplyAction="http://tempuri.org/ICriminalService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(WebClientContracts.CriminalDTO criminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/GetCriminals", ReplyAction="http://tempuri.org/ICriminalService/GetCriminalsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebUIClient.CriminalServiceReference.ValidationFault), Action="http://tempuri.org/ICriminalService/GetCriminalsValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        WebClientContracts.CriminalDTO[] GetCriminals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/GetCriminals", ReplyAction="http://tempuri.org/ICriminalService/GetCriminalsResponse")]
        System.Threading.Tasks.Task<WebClientContracts.CriminalDTO[]> GetCriminalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/SearchCriminals", ReplyAction="http://tempuri.org/ICriminalService/SearchCriminalsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebUIClient.CriminalServiceReference.ValidationFault), Action="http://tempuri.org/ICriminalService/SearchCriminalsValidationFaultFault", Name="ValidationFault", Namespace="http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")]
        bool SearchCriminals(WebClientContracts.CriminalDTO criminal, string[] emails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalService/SearchCriminals", ReplyAction="http://tempuri.org/ICriminalService/SearchCriminalsResponse")]
        System.Threading.Tasks.Task<bool> SearchCriminalsAsync(WebClientContracts.CriminalDTO criminal, string[] emails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICriminalServiceChannel : WebUIClient.CriminalServiceReference.ICriminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CriminalServiceClient : System.ServiceModel.ClientBase<WebUIClient.CriminalServiceReference.ICriminalService>, WebUIClient.CriminalServiceReference.ICriminalService {
        
        public CriminalServiceClient() {
        }
        
        public CriminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CriminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(WebClientContracts.CriminalDTO criminal) {
            base.Channel.Create(criminal);
        }
        
        public System.Threading.Tasks.Task CreateAsync(WebClientContracts.CriminalDTO criminal) {
            return base.Channel.CreateAsync(criminal);
        }
        
        public WebClientContracts.CriminalDTO[] GetCriminals() {
            return base.Channel.GetCriminals();
        }
        
        public System.Threading.Tasks.Task<WebClientContracts.CriminalDTO[]> GetCriminalsAsync() {
            return base.Channel.GetCriminalsAsync();
        }
        
        public bool SearchCriminals(WebClientContracts.CriminalDTO criminal, string[] emails) {
            return base.Channel.SearchCriminals(criminal, emails);
        }
        
        public System.Threading.Tasks.Task<bool> SearchCriminalsAsync(WebClientContracts.CriminalDTO criminal, string[] emails) {
            return base.Channel.SearchCriminalsAsync(criminal, emails);
        }
    }
}
